name: Notify Contributors on Push

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Get the list of contributors
      - name: Get contributors
        id: contributors
        run: |
          # Get the list of contributor emails (unique contributors to the repo)
          CONTRIBUTORS=$(git log --format='%ae' | sort -u | tr '\n' ',')
          echo "contributors=$CONTRIBUTORS" >> $GITHUB_OUTPUT

      # Step 3: Send email to contributors
      - name: Send email notification
        if: github.actor == 'thanhdong200425' 
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # SMTP server (e.g., Gmail)
          server_port: 587                # Port for TLS
          username: ${{ secrets.EMAIL_USERNAME }} 
          password: ${{ secrets.EMAIL_PASSWORD }}  
          subject: "New Commit Pushed to ${{ github.repository }}"
          to: ${{ steps.contributors.outputs.contributors }}  # List of contributor emails
          from: ${{ secrets.EMAIL_USERNAME }}  # Sender email
          body: |
            Hello contributors,

            A new commit has been pushed to ${{ github.repository }} by ${{ github.actor }}.
            Commit message: ${{ github.event.head_commit.message }}
            Commit URL: ${{ github.event.head_commit.url }}

            Please pull the latest changes to stay up-to-date!

            Regards,
            ${{ github.actor }}
